dist: trusty
sudo: true
language: c
compiler:
  - gcc
  - clang

before_install:
  - travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.4.tar.gz | tar xz
  - cd SDL2-2.0.4
  - ./configure
  - make
  - sudo make install
  - cd ..

script:
  - ./build.sh
