
static const char controls_text[] =
"\n"
"| Basic Controls    | Description |\n"
"| ------------------|-------------|\n"
"| Left (or Up)      | Previous image(s) or pan if appropriate |\n"
"| Right (or Down)   | Next image(s) or pan if appropriate |\n"
"| Space             | Next image(s) |\n"
"| CTRL + Space      | Previous image(s) |\n"
"| CTRL + Direction  | Next or previous image(s) even when zoomed in |\n"
"| +/-               | Zoom in/out |\n"
"| Mouse Wheel       | Zoom in/out |\n"
"| Left click + drag | Pan around a zoomed in image |\n"
"| A                 | Actual size |\n"
"| F                 | Toggle fill screen mode |\n"
"| Home              | Go to first image in the list |\n"
"| End               | Go to last image in the list |\n"
"| M                 | Shuffle (Mix) the images (only in single mode) |\n"
"| N                 | Sort the images by file name (only in single mode) |\n"
"| CTRL+N            | Sort the images by file path (only in single mode) |\n"
"| Z                 | Sort the images by size (only in single mode) |\n"
"| T                 | Sort the images by last modified (only in single mode) |\n"
"| CTRL + F or F11   | Toggle Fullscreen |\n"
"| ESC               | Exit or \"Back\" similar to Android |\n"
"| L/R               | Rotate the current image 90 degrees left/right |\n"
"| CTRL + L/R        | Rotate the current image arbitrary degrees (popup GUI) |\n"
"| H/V               | Flip the current image horizontally/vertically |\n"
"| S                 | Save current image(s) to current playlist |\n"
"| CTRL + S          | Remove current image(s) from current playlist |\n"
"| Delete            | Delete the current image and move to the next (only in single mode) |\n"
"| Backspace         | Remove the current image and move to the next (only in single mode) |\n"
"| CTRL + 1          | Single image mode |\n"
"| CTRL + 2          | Double image mode |\n"
"| CTRL + 4          | Quad image mode   |\n"
"| CTRL + 8          | 8 image mode      |\n"
"| CTRL + U          | Thumbnail mode    |\n"
"| CTRL + I          | List mode    |\n"
"| F1 - F10          | Start a slideshow with 1 - 10 second delay |\n"
"\n"
"\n"
"For GIFS there are extra controls, though the progress bar is only\n"
"displayed if you are viewing a GIF in single image mode:\n"
"\n"
"| GIF Controls            | Description |\n"
"| --------------------    |-------------|\n"
"| CTRL + +/-              | Speed up or slow down an animated gif |\n"
"| CTRL + Mouse Wheel      | Speed up or slow down an animated gif |\n"
"| P                       | Pause/Unpause gif |\n"
"| Mouse over progress bar | Pause |\n"
"| Wheel over progress bar | Scroll through frames |\n"
"| click/drag progress bar | select/scroll frames |\n"
"\n"
"\n"
"Vim Inspired Thumb Mode\n"
"=======================\n"
"Switch with CTRL+U to viewing all your current images as thumbnails on a vertically\n"
"scrolling plane.  Animated GIF thumbnails are generated from the first frame.\n"
"You can use the arrows and mouse and scrollwheel to move around\n"
"and select an image but if you're a vim user you'll feel right at home.\n"
"Note the basic controls above are based on scancode (ie what you see on the\n"
"physical key, what the hardware actually sends, not any custom layout you have in\n"
"software) while the Thumbmode controls are based on keycode and do respect your\n"
"layout (otherwise you lose all that vim muscle memory).  This is irrelevant\n"
"to most people but for people like myself who use Dvorak and *don't* change\n"
"the default Vim keybinds, HJKL, are JCVP physically.\n"
"\n"
"| Thumbmode Controls    | Description |\n"
"| --------------------  |-------------|\n"
"| Arrow Keys or HJKL    | Move around |\n"
"| Mouse Wheel           | Move up and down |\n"
"| g or Home             | Move to first image |\n"
"| G or End              | Move to last image |\n"
"| Click                 | Move to that image |\n"
"| CTRL + Click          | Select multiple arbitrary images |\n"
"| SHIFT + Click         | Select a contiguous range of images |\n"
"| Enter or Double Click | Change to normal mode on current image |\n"
"| CTRL + HJKL           | Adjust the number of rows and columns shown |\n"
"| V                     | Enter Visual Selection Mode |\n"
"| SHIFT + V             | Enter Visual Line Selection Mode |\n"
"| Backspace or R        | Removes current selection from the list |\n"
"| X                     | Removes and possibly Deletes current selection |\n"
"| CTRL + Backspace/R/X  | Invert action (remove/delete unselected items) |\n"
"| S                     | Save current image(s) to current playlist |\n"
"| CTRL + S              | Remove current image(s) from current playlist |\n"
"| /                     | Start typing a search |\n"
"| /pattern + ENTER      | Enter \"Results mode\" (cycle with n/N) |\n"
"| CTRL + ENTER          | (in results mode) View results |\n"
"| ESC                   | Exit or \"Back\" similar to Android |\n"
"| CTRL + C              | Same as Vim, almost the same as ESC but can't exit thumbmode |\n"
"\n"
"The number of rows and columns can also be set in Preferences, as well as whether X deletes\n"
"instead of just removing the selection.\n"
"\n"
"List Mode\n"
"=========\n"
"Switch with CTRL+I to view a list of all your current images with columns showing the\n"
"name, size, and last modified time.  You can select the column headings to sort by that,\n"
"ascending or descending.  You can scroll through the list or use up and down.  Hitting\n"
"Enter or double clicking will go back to normal mode on that image.\n"
"\n"
"Type something in the search bar at the top and hit enter to show a list of files that match.\n"
"Same controls as normal list mode, but if you hit enter or double click you will be in \"View\n"
"Results\" mode, which is normal mode but only viewing the results (same as from thumb search).\n"
"ESC to backs out of View Results, Results, and list mode entirely.\n"
"\n";

